/**
 * Regenerates `src/typebox.bundle.ts`.
 *
 * typebox ships as 691 separate ESM modules totalling only ~850 KB of code.
 * The code is not the problem, the module count is: Node allocates a module
 * record, a namespace object and compiled code per module, which for this
 * package costs 20-25 MB of RSS before a single schema is built. Every
 * delegated child pays it, because tool-call validation is on the hot path.
 *
 * Bundling the three entry points we use into one module removes that overhead
 * without changing a line of typebox's own logic:
 *
 *     import { Compile } from "typebox/compile"   node/tsx +24.2 MB   bun +35.4 MB
 *     the same code, bundled                               +1.8 MB        +12.1 MB
 *
 * The bundle is checked in because delegated workers run from source and never
 * see a build step. `test/typebox-bundle.test.ts` fails if the checked-in
 * bundle no longer matches the installed typebox, so a dependency bump cannot
 * quietly leave a stale copy behind. Rerun this when it does:
 *
 *     npm run bundle-typebox
 */
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(join(packageRoot, "package.json"));

/** typebox's exports map does not expose ./package.json, so walk up from the entry. */
function installedTypeboxVersion(): string {
	let dir = dirname(require.resolve("typebox"));
	for (let i = 0; i < 10; i++) {
		const manifest = join(dir, "package.json");
		if (existsSync(manifest)) {
			const parsed = JSON.parse(readFileSync(manifest, "utf8")) as { name?: string; version?: string };
			if (parsed.name === "typebox" && parsed.version) return parsed.version;
		}
		const parent = dirname(dir);
		if (parent === dir) break;
		dir = parent;
	}
	throw new Error("could not determine the installed typebox version");
}

export const TYPEBOX_VERSION_MARKER = "TYPEBOX_VERSION";

function main(): void {
	const version = installedTypeboxVersion();
	const entry = join(packageRoot, "src", ".typebox-entry.mjs");
	const out = join(packageRoot, "src", ".typebox-bundle.mjs");

	writeFileSync(
		entry,
		'export { Type } from "typebox";\nexport { Compile } from "typebox/compile";\nexport { Value } from "typebox/value";\n',
	);
	try {
		execFileSync("bun", ["build", entry, "--target=node", "--format=esm", `--outfile=${out}`], {
			cwd: packageRoot,
			stdio: "inherit",
		});

		const header = `// This file is auto-generated by scripts/bundle-typebox.ts
// Do not edit manually - run 'npm run bundle-typebox' to update
//
// typebox ${version}, bundled from "typebox", "typebox/compile" and
// "typebox/value" into a single module. typebox is 691 tiny ESM modules and
// Node charges 20-25 MB of RSS for the module records alone; this is the same
// code with that overhead removed. Import it through ./typebox.ts, which puts
// the real types back on.
//
// ${TYPEBOX_VERSION_MARKER} ${version}

// @ts-nocheck
`;
		writeFileSync(join(packageRoot, "src", "typebox.bundle.ts"), header + readFileSync(out, "utf8"));
		console.log(`Generated src/typebox.bundle.ts from typebox ${version}`);
	} finally {
		rmSync(entry, { force: true });
		rmSync(out, { force: true });
	}
}

main();
