/**
 * Emits `src/models.generated.ts`.
 *
 * The catalogue used to be emitted as a 630 KB TypeScript object literal. That
 * cost ~9 MB of RSS to import, because V8 has to parse that much source and
 * materialise all ~1265 model objects before anything can look up one model.
 *
 * It is emitted as a JSON string literal parsed at load instead. V8 parses JSON
 * considerably faster than the equivalent source and holds the result more
 * compactly, which takes the same import from +9.0 MB to +4.7 MB under
 * node/tsx and from +8.4 MB to +4.2 MB under bun.
 *
 * Nothing is given up to get that. The per-model `Model<"...">` entries in the
 * emitted `ModelCatalogue` type are erased at runtime, so they are free, and
 * they preserve exactly what the old `as const` object gave callers: `keyof`
 * per provider, the `api` inference `models.ts` does to type `getModel`, and
 * the `compat` narrowing that hangs off it.
 *
 * The data stays inside the `.ts` deliberately. A sibling `.json` file measured
 * slightly better under node, but the package build only includes TypeScript
 * sources and neither tsc nor tsgo copies non-TS assets, so it would need a
 * copy step in `build` and would break the published package the first time
 * that step was forgotten.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Model } from "../src/types.js";

export function emitModels(providers: Record<string, Record<string, Model<any>>>, packageRoot: string): void {
	// Sort providers and model ids so output is deterministic and diffs stay readable.
	const data: Record<string, Record<string, Model<any>>> = {};
	for (const providerId of Object.keys(providers).sort()) {
		const models = providers[providerId];
		const sorted: Record<string, Model<any>> = {};
		for (const modelId of Object.keys(models).sort()) {
			sorted[modelId] = models[modelId];
		}
		data[providerId] = sorted;
	}

	let output = `// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update
//
// The catalogue is a JSON string parsed at load rather than an object literal:
// the same values, materially less memory to import. Only the types below are
// TypeScript, and types are erased at runtime, so they cost nothing.

import type { Model } from "./types.js";

export type ModelCatalogue = {
`;
	for (const providerId of Object.keys(data)) {
		output += `\t${JSON.stringify(providerId)}: {\n`;
		for (const modelId of Object.keys(data[providerId])) {
			output += `\t\t${JSON.stringify(modelId)}: Model<${JSON.stringify(data[providerId][modelId].api)}>;\n`;
		}
		output += `\t};\n`;
	}
	output += `};

export const MODELS = JSON.parse(${JSON.stringify(JSON.stringify(data))}) as ModelCatalogue;
`;

	writeFileSync(join(packageRoot, "src/models.generated.ts"), output);
}
